### ISSUE TITLE
合并弹幕和字幕时出错

### ISSUE THREAD

**Issue by Z-fly** [hoshinohikari/Assmodhelper#1]
文件提取自 https://www.bilibili.com/video/BV1dN411R7N4 & https://www.bilibili.com/bangumi/play/ep380839

[弹幕.ass.txt](https://github.com/hoshinohikari/Assmodhelper/files/5975087/ass.txt)
[字幕.ass.txt](https://github.com/hoshinohikari/Assmodhelper/files/5975088/ass.txt)

**Comment by Z-fly** [comment]
能否针对这个需求适配下，非常感谢！

**Comment by hoshinohikari** [comment]
fixed，请下载最新版

**Comment by Z-fly** [comment]
新版确实没问题了！
![image](https://user-images.githubusercontent.com/10470892/107873107-c1eefe00-6eea-11eb-820c-0a7399bfdc0e.png)
顺便提一下，一个新的小BUG。
在程序打开的时候，上下方向键应该是默认禁用的。
@hoshinohikari

**Comment by hoshinohikari** [comment]
好，我是sb
